title: VampireTonic
description: "A hauntingly beautiful Jekyll theme with deep crimson accents glowing against shadowy backgrounds, featuring elegant gothic typography perfect for dark poetry, mysterious stories, and content that thrives in eternal night."
encoding: utf-8

# Theme settings
author: "Your Name"
email: "your.email@example.com"
baseurl: ""
url: ""

# Vampire theme colors
theme_colors:
  primary: "#8B0000"      # Dark red
  secondary: "#2F1B14"    # Dark brown
  accent: "#DC143C"       # Crimson
  background: "#0D0D0D"   # Near black
  text: "#E8E8E8"         # Light gray
  muted: "#696969"        # Dim gray

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock", "node_modules", "vendor"]