source "https://rubygems.org"

# Jekyll and plugins
gem "jekyll", "~> 4.4.0"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# Theme dependencies
gem "sassc", "~> 2.1"
gem "rouge", "~> 4.0"
gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm", "~> 1.1"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Development dependencies
group :development, :test do
  gem "html-proofer", "~> 5.0"
  gem "rspec", "~> 3.0"
end
